# Copyright © UChicago Argonne LLC
# See LICENSE file for details
params = [
    {
        "name": "Ylow",
        "type": "int",
        "value": 0,
        "suffix": " pixel",
        "tip": "The minimum Y pixel to include in the spectra",
        "pv": "27idmot1:YLowPixel",
    },
    {
        "name": "Yhigh",
        "type": "int",
        "value": 256,
        "suffix": " pixel",
        "tip": "The maximum Y pixel to include in the spectra",
        "pv": "27idmot1:YHighPixel",
    },
    {
        "name": "RefL",
        "type": "float",
        "value": 70,
        "suffix": " pixel",
        "tip": "Pixel number in the center of the energy dispersion on the lambda detector",
        "pv": "27idmot1:Merix_refChan",
        "format": "{value:.3f} {suffix}",
        "step": 0.001,
    },
    {
        "name": "Acrystalsize",
        "type": "float",
        "value": 1.3,
        "suffix": " mm",
        "tip": "Dice size of analyzer",
        "pv": "27idmot1:Acrystal",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
    },
    {
        "name": "Eb",
        "type": "float",
        "value": 10.0,
        "suffix": " keV",
        "tip": "Backscattering energy of analyzer",
        "pv": "27idmot1:Merix_E0",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
        "siPrefix": False,
    },
    {
        "name": "Ra",
        "type": "float",
        "value": 1900.0,
        "suffix": " mm",
        "tip": "Radius of Rowland circle",
        "pv": "27idmot1:Merix_RA",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
        "siPrefix": False,
    },
    {
        "name": "DeltaD",
        "type": "float",
        "value": 20e-3,
        "suffix": " mm",
        "tip": "Detector pixel width in the energy dispersion direction",
        "pv": "27idmot1:LambdaPixelSize",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
        "siPrefix": False,
    },
    {
        "name": "E",
        "type": "float",
        "value": 10.0,
        "suffix": " keV",
        "tip": "Current energy of analyzer",
        "pv": "27idmot1:Merix_E.VAL",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
        "siPrefix": False,
    },
    {
        "name": "ThetaB",
        "type": "float",
        "value": 0.0,
        "suffix": " µrad",
        "tip": "Bragg angle of analyzer",
        "pv": "27idmot1:Merix_Theta.VAL",
        "format": "{value:.6f} {suffix}",
        "step": 1e-6,
        "siPrefix": False,
    },
    {
        "name": "TiltAngle",
        "type": "float",
        "value": 0.0,
        "suffix": " degree",
        "tip": "Tilt angle of the detector",
        "pv": "none",
        "format": "{value:.3f} {suffix}",
        "step": 1e-3,
        "siPrefix": False,
    },
    {
        "name": "NEnergyBins",
        "type": "int",
        "value": 0,
        "suffix": " bins",
        "tip": "Number of bins for binning the spectra",
        "pv": "27idmot1:BinNumber.VAL",
        "format": "{value:d} {suffix}",
        "step": 1,
        "siPrefix": False,
    },
]

unit_map = {p["name"]: p.get("suffix", "") for p in params}
